apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-keycloak-2 
  labels:
    app: nfs-keycloak-2
  namespace: keycloak
spec:
  storageClassName: ""
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  mountOptions: 
    - hard   
    - nfsvers=4.2
  nfs:
    path: "/keycloak2/conf"
    server: nfs-server.nfs.svc.cluster.local
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-keycloak-2
  labels:
    app: nfs-keycloak-2
  namespace: keycloak
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-keycloak-2

